# Generated by Django 5.0.6 on 2024-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_logos_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Статистика в цифрах',
            },
        ),
    ]
