# Generated by Django 5.0.6 on 2024-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_benefit_title_benefit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
