# Generated by Django 5.0.6 on 2024-07-02 19:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_history_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='news/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
