# Generated by Django 5.0.6 on 2024-07-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_news_date_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата публикации'),
        ),
    ]
