# Generated by Django 5.0.6 on 2024-07-03 06:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, verbose_name='Дата публикации')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('announcement', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('image', models.FileField(blank=True, upload_to='projects/', verbose_name='Картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
