# Generated by Django 5.0.6 on 2024-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(related_name='сategories', to='catalog.category', verbose_name='Направления'),
        ),
    ]
