# Generated by Django 5.0.6 on 2024-07-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='product',
            field=models.ManyToManyField(related_name='products', to='catalog.product', verbose_name='Товары'),
        ),
    ]
