# Generated by Django 5.0.6 on 2024-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_productapplication_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид песка'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид песка'),
        ),
    ]
