# Generated by Django 5.0.6 on 2024-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_remove_application_type_application_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapplication',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Направление'),
        ),
    ]
