# Generated by Django 5.0.6 on 2024-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_application_deadlines_application_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapplication',
            name='deadlines',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сроки поставки'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='package',
            field=models.CharField(blank=True, max_length=100, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='productapplication',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Объем (м3)'),
        ),
    ]
