# Generated by Django 5.0.6 on 2024-11-29 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_productapplication_deadlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='text_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='icon_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='text_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография ALT'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография ALT'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография ALT'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография ALT'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография TITLE'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография TITLE'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография TITLE'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фотография TITLE'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='text_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_for_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='history',
            name='announcement_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='announcement_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='announcement_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='year_en',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='year_kz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='year_ru',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='logos',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_for_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для Slug'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='number',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='text_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractions_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Фракции песка'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractions_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Фракции песка'),
        ),
        migrations.AddField(
            model_name='product',
            name='fractions_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Фракции песка'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='product',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_for_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид песка'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид песка'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид песка'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ALT'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото TITLE'),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='projects',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_for_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок для Slug'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка ALT'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='step',
            name='image_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка TITLE'),
        ),
        migrations.AddField(
            model_name='step',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_alt_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка ALT'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='structure',
            name='icon_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка TITLE'),
        ),
        migrations.AddField(
            model_name='structure',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='text_kz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='application',
            name='deadlines',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сроки поставки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='package',
            field=models.CharField(blank=True, max_length=255, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объем (м3)'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.FileField(blank=True, upload_to='benefits/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.FileField(upload_to='logos/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='number',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вид песка'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='deadlines',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сроки поставки'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='package',
            field=models.CharField(blank=True, max_length=255, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productapplication',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объем (м3)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на библиотеку'),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='order',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.FileField(blank=True, upload_to='steps/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='icon',
            field=models.FileField(blank=True, upload_to='structure/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
