# Generated by Django 5.0.6 on 2025-01-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_advantage_image_alt_advantage_image_alt_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
