# Generated by Django 5.0.6 on 2024-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
