# Generated by Django 5.0.6 on 2024-06-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_logos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
