# Generated by Django 5.0.6 on 2024-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_benefit_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, upload_to='structure/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Состав песка',
            },
        ),
    ]
