# Generated by Django 5.0.6 on 2024-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('announcement', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Хронология',
            },
        ),
    ]
