# Generated by Django 5.0.6 on 2024-07-02 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
