# Generated by Django 5.0.6 on 2024-07-02 15:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_history_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
