# Generated by Django 5.0.6 on 2024-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_category_image_category_text_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
