# Generated by Django 5.0.6 on 2024-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_category_order_alter_category_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='categories/', verbose_name='Фотография'),
        ),
    ]
