# Generated by Django 5.0.6 on 2024-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
