# Generated by Django 5.0.6 on 2024-07-03 12:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_advantage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Вид песка')),
                ('fractions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Фракции песка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('category', models.ManyToManyField(related_name='products', to='catalog.category', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
