# Generated by Django 5.0.6 on 2024-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_projects_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='catalog.category', verbose_name='Направления'),
        ),
    ]
