# Generated by Django 5.0.6 on 2024-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='product',
            field=models.ManyToManyField(related_name='products_projects', to='catalog.product', verbose_name='Товары'),
        ),
    ]
