# Generated by Django 5.0.6 on 2024-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_productphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки с сайта',
            },
        ),
    ]
