# Generated by Django 5.0.6 on 2024-07-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='Продукт')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('status', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Онлайн заявки с сайта'},
        ),
    ]
